### ISSUE TITLE
Post goal is failing

### ISSUE THREAD

**Issue by ascuccimarra** [tarmac/pregnancy-control#167]
2016-01-28 13:37:28,164 [http-bio-127.6.173.129-8080-exec-24] ERROR errors.GrailsExceptionResolver  - NullPointerException occurred when processing request: [POST] /goal/setGoal
Cannot invoke method instanceOf() on null object. Stacktrace follows:
java.lang.NullPointerException: Cannot invoke method instanceOf() on null object
	at gsp_simpleCare_goals_goalsModal_modalFields_gsp.run(gsp_simpleCare_goals_goalsModal_modalFields_gsp.groovy:16)
	at gsp_simpleCare_goals_goalsModal_modalContent_gsp$_run_closure1.doCall(gsp_simpleCare_goals_goalsModal_modalContent_gsp.groovy:31)
	at gsp_simpleCare_goals_goalsModal_modalContent_gsp.run(gsp_simpleCare_goals_goalsModal_modalContent_gsp.groovy:36)
	at io.tarmac.api.GoalController.setGoal(GoalController.groovy:45)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at net.bull.javamelody.JspWrapper.invoke(JspWrapper.java:150)
	at net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:286)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:200)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:178)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
	at grails.plugin.springsecurity.rest.RestAuthenticationFilter.doFilter(RestAuthenticationFilter.groovy:143)
	at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:53)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:62)
	at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ppazos** [comment]
@ascuccimarra 

The problem is when the measureCodeDef is wrong.

1. It should return a JSON error with content type application/json
2. and status code 400 Bad Request
